[General]
network = ned.CityNetwork
sim-time-limit = 3000s
ned-path = ned
parallel-simulation = false
##################################################
# Automatic experiment runs
##################################################
repeat = 10
seed-set = ${repetition}
#output-scalar-file = results/${configname}-run${runnumber}.sca
#output-vector-file = results/${configname}-run${runnumber}.vec

##################################################
# Global parameters
##################################################
*.numIntersections = 4

# IMPORTANT: use the exact names your Controller.cc expects
# In your code it seems: SDTLP, SDTLP_MULTI, FCFS, NO_PREEMPT,SDTLP_CLOSEST
 
*.controller.L = 4.5m
*.controller.MG = 2.5m
*.controller.roadSegmentLength = 300m

**.inter[*].stabilityExtra = 5s
*.inter[*].fixedWindow = 300s

##################################################
# Traffic parameters
##################################################
# low = 10s, medium = 5s, high = 3.5s
*.inter[*].arrivalMean = ${traffic=10s,5s,3.5s}
*.inter[*].normalSpeed = 9.72
*.inter[*].queueMax = 50

##################################################
# Scenario 1: One EV
##################################################
[Config Scenario1_OneEV]

# For Scenario 1, only SDTLP and No Preemption are meaningful
*.controller.method = ${method="SDTLP","NO_PREEMPT"}
*.inter[*].method = ${method}
output-scalar-file = results/${configname}-${method}-${traffic}-seed${repetition}.sca
output-vector-file = results/${configname}-${method}-${traffic}-seed${repetition}.vec
*.numEVs = 1
*.controller.scenarioName = "${configname}"
*.controller.trafficLevel = "${traffic}"
*.controller.seedValue = ${repetition}
*.ev[0].evId = 0
*.ev[0].severity = 2
*.ev[0].startPos = uniform(-300m, -50m)
#*.ev[0].startPos = -300m
*.ev[0].destinationPos = 300m
*.ev[0].speed = 16.67mps
*.ev[0].approach = 3
*.ev[0].startTime = 300s

##################################################
# Scenario 2: Two EVs, different priority
##################################################
[Config Scenario2_TwoEV_DiffSeverity_LowerFirst]
*.controller.method = ${method="SDTLP_MULTI","SDTLP_CLOSEST","NO_PREEMPT","FCFS"}
*.inter[*].method = ${method}
output-scalar-file = results/${configname}-${method}-${traffic}-seed${repetition}.sca
output-vector-file = results/${configname}-${method}-${traffic}-seed${repetition}.vec
*.numEVs = 2
*.controller.scenarioName = "${configname}"
*.controller.trafficLevel = "${traffic}"
*.controller.seedValue = ${repetition}
# EV1: higher priority
*.ev[0].evId = 0
*.ev[0].severity = 1
#*.ev[0].startPos = -300m
*.ev[0].startPos = uniform(-300m, -50m)
*.ev[0].destinationPos = 300m
*.ev[0].speed = 16.67mps
*.ev[0].approach = 3
*.ev[0].startTime = 300s

# EV2: lower priority
*.ev[1].evId = 1
*.ev[1].severity = 3
#*.ev[1].startPos = 299m
*.ev[1].startPos = uniform(50m, 300m)
*.ev[1].destinationPos = -300m
*.ev[1].speed = -16.67mps
*.ev[1].approach = 1
*.ev[1].startTime = 300s

##################################################
# Scenario 3: Two EVs, same priority
##################################################
[Config Scenario3_TwoEV_SameSeverity]
*.controller.method = ${method="SDTLP_MULTI","SDTLP_CLOSEST","NO_PREEMPT","FCFS"}
*.inter[*].method = ${method}
output-scalar-file = results/${configname}-${method}-${traffic}-seed${repetition}.sca
output-vector-file = results/${configname}-${method}-${traffic}-seed${repetition}.vec
*.numEVs = 2
*.controller.scenarioName = "${configname}"
*.controller.trafficLevel = "${traffic}"
*.controller.seedValue = ${repetition}
# EV1
*.ev[0].evId = 0
*.ev[0].severity = 2
#*.ev[0].startPos = -300m
*.ev[0].startPos = uniform(-300m, -50m)
*.ev[0].destinationPos = 300m
*.ev[0].speed = 16.67mps
*.ev[0].approach = 3
*.ev[0].startTime = 300s

# EV2
*.ev[1].evId = 1
*.ev[1].severity = 2
#*.ev[1].startPos = 200m
*.ev[1].startPos = uniform(50m, 300m)
*.ev[1].destinationPos = -300m
*.ev[1].speed = -16.67mps
*.ev[1].approach = 1
*.ev[1].startTime = 306s

##################################################
# Scenario 4: Three EVs
##################################################
[Config Scenario4_ThreeEV]
*.controller.method = ${method="SDTLP_MULTI","SDTLP_CLOSEST","NO_PREEMPT","FCFS"}
*.inter[*].method = ${method}
output-scalar-file = results/${configname}-${method}-${traffic}-seed${repetition}.sca
output-vector-file = results/${configname}-${method}-${traffic}-seed${repetition}.vec
*.numEVs = 3
*.controller.scenarioName = "${configname}"
*.controller.trafficLevel = "${traffic}"
*.controller.seedValue = ${repetition}
# EV1
*.ev[0].evId = 0
*.ev[0].severity = 3
#*.ev[0].startPos = -300m
*.ev[0].startPos = uniform(-300m, -50m)
*.ev[0].destinationPos = 300m
*.ev[0].speed = 16.67mps
*.ev[0].approach = 3
*.ev[0].startTime = 300s

# EV2
*.ev[1].evId = 1
*.ev[1].severity = 3
#*.ev[1].startPos = 250m
*.ev[1].startPos = uniform(50m, 300m)
*.ev[1].destinationPos = -300m
*.ev[1].speed = -16.67mps
*.ev[1].approach = 1
*.ev[1].startTime = 303s

# EV3: highest priority
*.ev[2].evId = 2
*.ev[2].severity = 1
#*.ev[2].startPos = 200m
*.ev[2].startPos = uniform(50m, 250m)
*.ev[2].destinationPos = -200m
*.ev[2].speed = -16.67mps
*.ev[2].approach = 0
*.ev[2].startTime = 306s