[General]
network = ned.CityNetwork
sim-time-limit = 1800s
ned-path = ned


##################################################
# Global parameters
##################################################
*.numIntersections = 4
*.controller.method = "SDTLP_MULTI" #SDTLP, SDTLP_MULTI,FCFS,NO_PREEMPTION
*.controller.L = 4.5m
*.controller.MG = 2.5m
*.controller.roadSegmentLength = 300m
#*.controller.useFixedFcfsDD = true#added
#*.controller.fixedFcfsDD = 150m#added
**.inter[*].stabilityExtra = 5s
*.inter[*].fixedWindow = 300s #for B metrics
##################################################
# Traffic parameters (set once)
##################################################
*.inter[*].arrivalMean =10 s      # low traffic (change to 5s / 2.5s)
*.inter[*].normalSpeed = 9.72     # 35 km/h in m/s
*.inter[*].queueMax = 50

##################################################
# ---------- Scenario 1: One EV ----------
##################################################
[Config Scenario1_OneEV]
#repeat = 5

# iterate the seed-set itself
seed-set = ${42, 43, 44, 45, 46}

*.numEVs = 1

*.ev[0].evId = 0
*.ev[0].severity = 2
*.ev[0].startPos = -300m
*.ev[0].destinationPos = 300m
*.ev[0].speed = 16.67mps
*.ev[0].approach = 3          # West -> East, enters from West
*.ev[0].startTime = 300s

##################################################
# ---------- Scenario 2: Two EVs, diff priority ----------
##################################################
[Config Scenario2_TwoEV_DiffSeverity_LowerFirst]
#repeat = 5

# iterate the seed-set itself
seed-set = ${42, 43, 44, 45, 46}


**.numEVs = 2

# EV1  
*.ev[0].evId = 0
*.ev[0].severity = 1
*.ev[0].startPos = -300m
*.ev[0].destinationPos = 300m
*.ev[0].speed = 16.67mps
*.ev[0].approach = 3          # West -> East
*.ev[0].startTime = 300s

# EV2  
*.ev[1].evId = 1
*.ev[1].severity = 3
*.ev[1].startPos = 299m # the difference to 300 m is it will reach destination 0.06 earlier (ver small)
*.ev[1].destinationPos = -300m
*.ev[1].speed = -16.67mps
*.ev[1].approach = 1         # East -> West, enters from East
*.ev[1].startTime = 300s

##################################################
# ---------- Scenario 3: Two EVs  ----------
##################################################
[Config Scenario3_TwoEV_SameSeverity]

#repeat = 5

# iterate the seed-set itself
seed-set = ${42, 43, 44, 45, 46}
**.numEVs = 2

# EV1 (higher priority, arrives first)
*.ev[0].evId = 0
*.ev[0].severity = 2
*.ev[0].startPos = -300m
*.ev[0].destinationPos = 300m
*.ev[0].speed = 16.67mps
*.ev[0].approach = 3          # West -> East
*.ev[0].startTime = 300s

# EV2 (lower priority, arrives later)
*.ev[1].evId = 1
*.ev[1].severity = 2
*.ev[1].startPos = 200m
*.ev[1].destinationPos = -300m
*.ev[1].speed = -16.67mps
*.ev[1].approach = 1      # East -> West
*.ev[1].startTime = 306s

##################################################
# ---------- Scenario 4: Three EVs ----------
##################################################
[Config Scenario4_ThreeEV]
#repeat = 5

# iterate the seed-set itself
seed-set = ${42, 43, 44, 45, 46}
 
*.numEVs = 3

# EV1
*.ev[0].evId = 0
*.ev[0].severity = 3
*.ev[0].startPos = -300m
*.ev[0].destinationPos = 300m
*.ev[0].speed = 16.67mps
*.ev[0].approach = 3          # West -> East
*.ev[0].startTime = 300s

# EV2
*.ev[1].evId = 1
*.ev[1].severity = 3
*.ev[1].startPos = 250m
*.ev[1].destinationPos = -300m
*.ev[1].speed = -16.67mps
*.ev[1].approach = 1          # East -> West
*.ev[1].startTime = 303s

# EV3: North -> South
*.ev[2].evId = 2
*.ev[2].severity = 1
*.ev[2].startPos = 200m
*.ev[2].destinationPos = -200m
*.ev[2].speed = -16.67mps
*.ev[2].approach = 0          # North -> South
*.ev[2].startTime = 306s
##################################################
# ---------- Scenario 5: Three EVs (ignore)----------
##################################################
[Config Scenario5_ThreeEV]
#repeat = 5

# iterate the seed-set itself
seed-set = ${42, 43, 44, 45, 46}



*.numEVs = 3

# EV1
*.ev[0].evId = 0
*.ev[0].severity = 3
*.ev[0].startPos = -300m
*.ev[0].destinationPos = 1200m
*.ev[0].speed = 16.67mps
*.ev[0].approach = 3          # West -> East
*.ev[0].startTime = 300s

# EV2
*.ev[1].evId = 1
*.ev[1].severity = 3
*.ev[1].startPos = 300m
*.ev[1].destinationPos = -300m
*.ev[1].speed = -16.67mps
*.ev[1].approach = 1          # East -> West
*.ev[1].startTime = 300s

# EV3 (highest priority)
*.ev[2].evId = 2
*.ev[2].severity = 1
*.ev[2].startPos = 0m
*.ev[2].destinationPos = 900m
*.ev[2].speed = 16.67mps
*.ev[2].approach = 0          # North  
*.ev[2].startTime = 300s